<?php
$this->inlineScript()->appendFile($this->basePath() . '/components/datatables/js/jquery.dataTables.min.js');
$this->inlineScript()->appendFile($this->basePath() . '/components/datatables/js/dataTables.bootstrap.js');
$this->headLink()->prependStylesheet($this->basePath() . '/components/datatables/css/jquery.dataTables.css');
$this->headLink()->prependStylesheet($this->basePath() . '/components/datatables/css/dataTables.bootstrap.css');
$title = $this->translate('Certificates');
$this->headTitle($title);
?>

<div class="container">
    <div class="row title-bar">
        <div class="col-xs-9">
            <h2><?php echo $title ?></h2>
        </div>
        <div class="col-xs-3">
            <a href="<?php echo $this->url('ce/certificates', array('action' => 'new')); ?>"
               class="btn btn-primary btn-lg pull-right">
                   <?php echo $this->translate('New certificate'); ?>
            </a>
        </div>
    </div>
    <div role="tabpanel" id="register-tab">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation"<?php if ($activeTab == 'active'): ?> class="active"<?php endif; ?>>
                <a href="#certificate-list-active" aria-controls="certificate-list-active" role="tab" data-toggle="tab" data-tab-name="active">
                    <?php echo $this->translate('Actives'); ?>
                </a>
            </li>
            <li role="presentation"<?php if ($activeTab == 'archive'): ?> class="active"<?php endif; ?>>
                <a href="#certificate-list-archive" aria-controls="certificate-list-archive" role="tab" data-toggle="tab" data-tab-name="archive">
                    <?php echo $this->translate('Archives'); ?>
                </a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <?php
            echo $this->partial('certificat/certificates/_tab', array(
                'tabId' => 'certificate-list-active',
                'tabIsActive' => ($activeTab == 'active') ? true : false,
                'certificates' => $activeCertificates
            ));
            ?>
            <?php
            echo $this->partial('certificat/certificates/_tab', array(
                'tabId' => 'certificate-list-archive',
                'tabIsActive' => ($activeTab == 'archive') ? true : false,
                'certificates' => $acrchivedCertificates
            ));
            ?>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
//<script>
    $(function () {
        // Add current url with active tab to browser history
        $('body').on('click', '.nav-tabs li:not(.active) a', function () {
            if (typeof history.pushState != 'undefined') {
                history.pushState(null, null, '?tab=' + $(this).data('tab-name'));
            }
        });

        // Init table
        $('table.certificate-list-table', '#certificate-list-active, #certificate-list-archive').DataTable({
            lengthChange: false,
            info: false,
            pagingType: "full_numbers",
            dom: "<'row'<'col-sm-12'tr>>" + "<'text-center'p>",
            language: {
                emptyTable: '<?php echo $this->translate('There are no certificates'); ?>.',
            },
            drawCallback: function (oSettings) {
                // Hide/Show pagination if count of page <= 1
                if (oSettings._iDisplayLength > oSettings.fnRecordsDisplay()) {
                    $(oSettings.nTableWrapper).find('.dataTables_paginate').hide();
                } else {
                    $(oSettings.nTableWrapper).find('.dataTables_paginate').show();
                }
            }
        });

        // Filter table by search input or date range
        $('body').on('change keyup', '.tab-pane.active .filter-bar input', function () {
            var $input = $(this),
                    table = $(this).closest('.tab-pane.active').find('table.certificate-list-table').DataTable();

            if (!$input.hasClass('datepicker')) {
                table.search($input.val());
            }

            table.draw();
        });
    });

    // Custom filtering function for date column. Filtering between two values
    $.fn.dataTable.ext.search.push(
            function (settings, data, dataIndex) {
                var min = $('#certificiates-from-filter', '.tab-pane.active').datepicker('getDate');
                var max = $('#certificiates-to-filter', '.tab-pane.active').datepicker('getDate');
                // Date from table. Column `Creation date`. 
                // Need replace date format from dd-mm-yyyy to mm/dd/yyyy
                var columnDate = new Date(data[4].replace(/(\d{2})-(\d{2})-(\d{4})/, "$2/$1/$3"));

                if ((isNaN(min) && isNaN(max)) || (isNaN(min) && columnDate <= max) ||
                        (min <= columnDate && isNaN(max)) || (min <= columnDate && columnDate <= max)) {
                    return true;
                }
                return false;
            }
    );
//</script>
<?php $this->inlineScript()->captureEnd(); ?>