<?php
$this->headTitle($title);
$this->inlineScript()->appendFile($this->basePath() . '/scripts/jquery.iframe-transport.js');
?>
<div class="container">
    <?php
    $form->setAttribute('class', 'jq-validate vertical-form');
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>      
    <div class="row title-bar">
        <div class="col-md-5 title">
            <h2><?php echo $title; ?></h2>
        </div>
        <div class="col-md-7 actions">
            <?php
            echo $this->formElement($form->get('complete')
                            ->setAttributes(array(
                                'class' => 'btn btn-primary btn-lg',
                                'data-loading-text' => $this->translate('Wait') . '...',
                                'value' => $this->translate('Complete')
            )));
            ?>     
            <?php
            echo $this->formElement($form->get('draft')
                            ->setAttributes(array(
                                'class' => 'btn btn-default btn-lg',
                                'data-loading-text' => $this->translate('Wait') . '...',
                                'value' => $this->translate('Save Draft')
            )));
            ?>              
            <?php if (isset($certificate)): ?>
                <a href="#" class="btn btn-default btn-lg go-with-confirm" 
                   data-href="<?php echo $this->url('ce/certificates', array('action' => 'delete', 'id' => $certificate->id)) ?>"
                   data-confirm-text="<?php echo $this->translate('Are you sure?'); ?>">
                       <?php echo $this->translate('Delete'); ?>
                </a>
            <?php endif; ?>
            <a href="<?php echo $this->url('ce/certificates') ?>" 
               class="btn btn-default btn-lg">
                   <?php echo $this->translate('Cancel'); ?>
            </a>
        </div>
    </div>
    <div class="box-title"><?php echo $this->translate('Details'); ?></div>
    <div class="panel panel-default panel-lg">
        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="certificate-name"><?php echo $this->translate('Name'); ?></label>
                                <?php
                                echo $this->formElement($form->get('name')
                                                ->setAttributes(array(
                                                    'id' => 'certificate-name',
                                                    'class' => 'form-control',
                                                    'placeholder' => $this->translate('Certificate name')
                                )));
                                ?>
                            </div>
                            <div class="form-group">
                                <label for="certificate-template"><?php echo $this->translate('Template'); ?></label>
                                <?php
                                echo $this->formElement($form->get('template_id')
                                                ->setAttributes(array(
                                                    'id' => 'certificate-template',
                                                    'class' => 'form-control'
                                )));
                                ?>
                            </div>
                            <div class="form-group-value">
                                <p><strong><?php echo $this->translate('Status'); ?></strong></p>
                                <p class="text-capitalize"><?php echo $this->translate($status); ?></p>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="certificate-duration"><?php echo $this->translate('Duration (hours)'); ?></label>
                                        <?php
                                        echo $this->formElement($form->get('duration')
                                                        ->setAttributes(array(
                                                            'id' => 'certificate-duration',
                                                            'class' => 'form-control',
                                                            'placeholder' => $this->translate('Duration')
                                        )));
                                        ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="certificate-language"><?php echo $this->translate('Language'); ?></label>
                                        <?php
                                        echo $this->formElement($form->get('language')
                                                        ->setAttributes(array(
                                                            'id' => 'certificate-language',
                                                            'class' => 'form-control'
                                        )));
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="certificate-start-date"><?php echo $this->translate('Start date'); ?></label>
                                        <div class="input-group">
                                            <div class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></div>
                                            <?php
                                            echo $this->formElement($form->get('start_date')
                                                            ->setAttributes(array(
                                                                'id' => 'certificate-start-date',
                                                                'class' => 'form-control datepicker',
                                                                'placeholder' => $this->translate('Start date'),
                                                                'value' => (isset($certificate)) ? date('d/m/Y', strtotime($certificate->start_date)) : ''
                                            )));
                                            ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="certificate-end-date"><?php echo $this->translate('End date'); ?></label>
                                        <div class="input-group">
                                            <div class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></div>
                                            <?php
                                            echo $this->formElement($form->get('end_date')
                                                            ->setAttributes(array(
                                                                'id' => 'certificate-end-date',
                                                                'class' => 'form-control datepicker',
                                                                'placeholder' => $this->translate('End date'),
                                                                'value' => (isset($certificate)) ? date('d/m/Y', strtotime($certificate->end_date)) : ''
                                            )));
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php if ($template): ?>
                        <div class="form-group">
                            <label for="default-description"><?php echo $this->translate('Default description'); ?></label>
                            <div id="default-description">
                                <?php echo nl2br($template->additional_comment); ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="certificate-description"><?php echo $this->translate('Description'); ?></label>
                        <?php
                        echo $this->formTextarea($form->get('description')
                                        ->setAttributes(array(
                                            'id' => 'certificate-description',
                                            'class' => 'form-control',
                                            'style' => 'height: 90px;',
                                            'placeholder' => $this->translate('Enter your description here...')
                        )));
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-title"><?php echo $this->translate('Participants'); ?></div>
    <div class="panel panel-default">
        <div class="panel-body table-responsive vertical-form">
            <div class="filter-bar form-inline participants-import-row">
                <div class="form-group">
                    <label for="certificate-csv-file"><?php echo $this->translate('CSV file import'); ?></label>
                    <input type="file" class="form-control" id="certificate-csv-file" 
                           placeholder="<?php echo $this->translate('Select a file'); ?>"
                           data-empty-text="<?php echo $this->translate('Please choose file to import'); ?>"
                           data-error-text="<?php echo $this->translate('This file contains errors'); ?>"/>
                </div>
                <button id="certificate-csv-file-import" class="btn btn-primary"
                        data-href="<?php echo $this->url('ce/csv-to-json-for-certificate'); ?>"
                        data-loading-text="<?php echo $this->translate('Wait') . '...'; ?>">
                            <?php echo $this->translate('Import'); ?>
                </button>  
                <div id="import-counts" class="text-muted hide">
                    <p><?php echo sprintf($this->translate('%s rows imported with %s error(s)'), '<span id="success-count-import">0</span>', '<span id="error-count-import">0</span>'); ?>.</p>
                </div>
            </div>
            <table id="certificate-participant-table" class="table table-striped">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('First name'); ?></th>
                        <th><?php echo $this->translate('Last name'); ?></th>
                        <th><?php echo $this->translate('E-mail'); ?></th>
                        <th><?php echo $this->translate('Birth date'); ?></th>
                        <th style="min-width:60px;"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($participants) > 0): ?>
                        <?php foreach ($participants as $key => $participant): ?>    
                            <?php
                            echo $this->partial('certificat/certificates/_participant-row-editable', array(
                                'key' => $key,
                                'participant' => $participant
                            ));
                            ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
                <tfoot>
                    <tr id="new-participant-row" class="form-inline-editing">
                        <td>
                            <input id="certificate-participant-first-name" type="text" class="form-control input-sm"
                                   placeholder="<?php echo $this->translate('First name'); ?>" data-rule-nohtml="1"
                                   data-target-field="first_name"/>
                        </td>
                        <td>
                            <input id="certificate-participant-last-name" type="text" class="form-control input-sm"
                                   placeholder="<?php echo $this->translate('Last name'); ?>" data-rule-nohtml="1"
                                   data-target-field="last_name"/>
                        </td>
                        <td>
                            <input id="certificate-participant-email" type="email" class="form-control input-sm"
                                   placeholder="<?php echo $this->translate('E-mail'); ?>" data-rule-nohtml="1"
                                   data-target-field="email" unique="participant-email"/>
                        </td>
                        <td>
                            <div class="input-group">
                                <div class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></div>
                                <input id="certificate-participant-birth-date" data-date-format="dd/mm/yyyy"
                                       placeholder="<?php echo $this->translate('Birth date'); ?>" data-rule-nohtml="1"
                                       type="text" class="form-control input-sm datepicker"
                                       data-target-field="birthday"/>
                            </div>
                        </td>
                        <td>
                            <button id="add-participant" class="btn btn-sm btn-primary pull-right" type="button">
                                <?php echo $this->translate('Add'); ?>
                            </button>
                        </td>
                    </tr>   
                    <?php echo $this->partial('certificat/certificates/_participant-row-editable'); ?>
                </tfoot>
            </table>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
//<script>
    $(function () {
        var $startInput = $('#certificate-start-date'),
                $endInput = $('#certificate-end-date');

        if ($startInput.val() != '') {
            $endInput.datepicker('setStartDate', $startInput.val());
        }

        $('body').on('change', $startInput, function () {
            if ($startInput.datepicker('getDate') > $endInput.datepicker('getDate')) {
                $endInput.val('');
            }
            $endInput.datepicker('setStartDate', $startInput.val());
        });

        $('body').on('change', '#certificate-template', function () {
            var $obj = $(this),
                    $description;

            $.ajax({
                url: '<?php echo $this->url('ce/get-template-description', array('action' => 'get-description')); ?>/id/' + $obj.val()
            }).done(function (response) {
                if (response.success) {
                    $description = $('<p/>', {html: nl2br(response.description)});
                    $('#default-description').html($description);
                }
            });
        });
    });
//</script>
<?php $this->inlineScript()->captureEnd(); ?>
