<?php
/**
 * View script for lost password retrieval
 * 
 * @var $this->form         Lost password form from \SelfAssessment\Form\LostpasswordForm
 * @var $this->messages     Error Messages from form validation
 */
$title = $this->translate('Passwort vergessen');
$this->headTitle($title);
?>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-lg panel-default">
                <div class="panel-heading"><h2 class="block-title"><?php echo $title ?></h2></div>
                <div class="panel-body">
                    <?php
                    $form->setAttribute('action', $this->url('ce/lost-password'));
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group">
                        <label class="sr-only" for="lostpassword-form-email"><?php echo $this->translate('E-mail'); ?></label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="ico ico--mail"></span></div>
                            <?php
                            echo $this->formEmail($form->get('email')
                                            ->setAttributes(array(
                                                'id' => 'lostpassword-form-email',
                                                'class' => 'form-control input-lg',
                                                'placeholder' => $this->translate('E-mail')
                            )));
                            ?>
                        </div>
                    </div>
                    <div class="form-group form-group--last text-right">
                        <?php
                        echo $this->formElement($form->get('submit')
                                        ->setAttributes(array(
                                            'id' => 'lostpassword-form-submit',
                                            'class' => 'btn btn-primary btn-lg',
                                            'value' => $this->translate('Reset ')
                        )));
                        ?>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div><!-- panel -->
        </div><!-- col -->
    </div><!-- row -->       
</div><!-- container -->

