<?php
$title = $this->translate('Your organization has been approved');
?>
<?php print $this->doctype(); ?>
<html lang="<?php print $this->lang() ?>">
    <head>
        <meta charset="utf-8">
    </head>
    <body style="
          width: 100%;
          max-width: 600px;
          margin: 0 auto;
          font-family: Arial, Helvetica, sans-serif;">

        <div style="
             height: 160px;
             background-color: #8fc4d5;
             border-radius: 0 0px 15px 15px;
             -moz-border-radius: 0 0px 15px 15px;
             -webkit-border-radius: 0 0px 15px 15px;
             margin-bottom: 50px;">
            <a href="<?php print $this->serverURL; ?>">
                <img src="<?php print $this->serverURL; ?>/images/logo-certificat.png">
            </a>
        </div>

        <h1 style="
            color: #164a5b;
            font-size: 24px;
            text-transform: uppercase;
            padding-left: 30px;
            margin-bottom: 20px;">
            <?php print $this->escapeHtml($title); ?>
        </h1>
        <div style="
             background-color: #dff0f6;
             border-radius: 15px;
             -moz-border-radius: 15px;
             -webkit-border-radius: 15px;
             padding: 25px 35px;
             color: #164a5b;
             margin-bottom: 20px;;
             font-size: 15px;
             ">
            <p style="font-size: 18px; font-weight: 400;"><?php print $this->translate("Your organization has been approved. You can login with your e-mail address and your password now."); ?></p>
        </div>
        <div style="text-align: center; margin-bottom: 50px;">
            <div style="display: inline-block;">
                <a href="<?php print $this->serverURL; ?>"
                   style="
                   display: inline-block; 
                   color: #ea4f4f; 
                   font-size: 13px; 
                   padding: 0 20px; 
                   border-right: 1px solid;">
                   <?php print $this->serverURL; ?>
                </a>
                <a href="mailto: help@certificat.localhost"
                   style="
                   display: inline-block; 
                   color: #ea4f4f; 
                   font-size: 13px; 
                   padding: 0 20px;">
                    help@certificat.localhost
                </a>
            </div>
        </div>
        <div style="
             height: 100px;
             background-color: #164e60;
             border-radius:  15px 15px 0 0;
             -moz-border-radius: 15px 15px 0 0;
             -webkit-border-radius: 15px 15px 0 0;">
            <a href="#" style="
               margin: 30px 30px 0 0;
               float: right;
               display: inline-block;">
                <img src="<?php print $this->serverURL; ?>/images/logo-fond-social-europeen.png" >
            </a>
        </div>
    </body>
</html>