<?php echo $this->doctype(); ?>
<?php $title = $this->translate('SNJ Certificat'); ?>
<html lang="<?php echo $this->lang() ?>">
    <head>
        <?php echo $this->headTitle($title)->setSeparator(' - ')->setAutoEscape(false); ?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')

                // Additional Info 
                ->appendName('author', 'KREIOS - http://www.kreios.lu')
                ->appendName('copyright', 'KREIOS © 2014-' . date('Y'))
                ->appendName('description', 'Service National de la Jeunesse - Certificat')

                // Add to homescreen for Chrome on Android
                ->appendName('mobile-web-app-capable', 'yes')

                // Add to homescreen for Safari on iOS
                ->appendName('apple-mobile-web-app-capable', 'yes')
                ->appendName('apple-mobile-web-app-status-bar-style', 'black')
                ->appendName('apple-mobile-web-app-title', 'SNJ - Certificat')

                // Tile icon for Win8 (144x144 + tile color)
                ->appendName('msapplication-TileImage', '/images/touch/ms-touch-icon-144x144-precomposed.png')
                ->appendName('msapplication-TileColor', '#3372DF');
        ?>

        <!-- Add to homescreen for Chrome on Android -->
        <link rel="icon" sizes="192x192" href="/images/touch/chrome-touch-icon-192x192.png">

        <!-- Add to homescreen for Safari on iOS -->
        <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">

        <!-- Styles And Scripts -->
        <?php
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
        ?>

        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <header id="header" class="hidden-xs">
            <div class="container">
                <a href="<?php echo $this->url('ce/index') ?>" id="logo">
                    <img src="/images/logo-certificat.png" alt="Certificat" />
                </a>
                <?php
                echo $this->navigation('language_navigation')
                        ->setAcl($this->acl)
                        ->setRole($this->userRole)
                        ->menu()
                        ->setPartial('layout/language_navigation.phtml');
                ?>
                <?php if ($this->userRole != 'guest'): ?>
                    <div class="user-box">
                        <div class="user-box-infos">
                            <a class="user-box-name" href="<?php echo $this->url('ce/my-profile') ?>">
                                <?php echo $this->userFirstName; ?> <strong><?php echo $this->userFirstName; ?></strong>
                            </a>
                            <a class="user-box-type" href="<?php echo $this->url('ce/my-profile') ?>">
                                <?php echo $this->userRoleTitle($this->userRole); ?>
                            </a>
                        </div>
                        <div class="picture-and-menu">
                            <a class="profile-picture" href="<?php echo $this->url('ce/my-profile') ?>">
                                <?php echo $this->profilePicture(); ?>
                            </a>
                            <div class="user-box-menu dropdown">
                                <button aria-expanded="true" data-toggle="dropdown" id="user-menu" type="button" class="user-box-menu-btn"></button>
                                <?php
                                echo $this->navigation('personal_navigation')
                                        ->setAcl($this->acl)
                                        ->setRole($this->userRole)
                                        ->menu()
                                        ->setPartial('layout/personal_navigation.phtml');
                                ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </header>

        <nav id="main-nav" class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand visible-xs-block" href="<?php echo $this->url('ce/index') ?>">
                        <img src="/images/logo-certificat-mobile.png" alt="Certificat"/>
                    </a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="main-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if ($this->userRole === 'guest'): ?>
                            <?php
                            echo $this->navigation('meta_navigation')
                                    ->setAcl($this->acl)
                                    ->setRole($this->userRole)
                                    ->menu()
                                    ->setPartial('layout/guest_navigation.phtml');
                            ?>     
                        <?php else: ?>
                            <?php
                            echo $this->navigation('navigation')
                                    ->setAcl($this->acl)
                                    ->setRole($this->userRole)
                                    ->menu()
                                    ->setPartial('layout/default_navigation.phtml');
                            ?>                        
                        <?php endif; ?>
                    </ul>
                    <?php
                    echo $this->navigation('language_navigation')
                            ->setAcl($this->acl)
                            ->setRole($this->userRole)
                            ->menu()
                            ->setUlClass('visible-xs-block')
                            ->setPartial('layout/language_navigation.phtml');
                    ?>
                    <a href="<?php print $this->config(array('url-collection', 'self-assessment')); ?>"
                       id="self-assessment-button" class="btn btn-default navbar-btn pull-right">
                        Self-Assessment
                    </a>
                    <a href="<?php print $this->config(array('url-collection', 'eportfolio')); ?>"
                       id="eportfolio-button" class="btn btn-default navbar-btn pull-right">
                        ePortfolio
                    </a>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>

        <main id="main-content">
            <div class="container flash-messages">
                <?php echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning')); ?>
                <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success')); ?>
                <?php echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-danger')); ?>
                <?php echo $this->flashMessenger()->render('info', array('alert', 'alert-dismissible', 'alert-info')); ?>
            </div>
            <?php echo $this->content; ?>
        </main>

        <footer id="footer">
            <div class="container">
                <?php
                echo $this->navigation('meta_navigation')
                        ->setAcl($this->acl)
                        ->setRole($this->userRole)
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setPartial('layout/footer_navigation.phtml');
                ?>
                <img id="logo-eu" src="/images/logo-fond-social-europeen.png"/>
            </div><!-- /.container -->
        </footer>
        <?php
        echo $this->plugin('InlineScript')
                ->appendFile($this->basePath() . '/scripts/validation/localization/messages_' . $this->lang() . '.js')
                ->appendFile($this->basePath() . '/scripts/validation/localization/methods_' . $this->lang() . '.js');
        ?>
    </body>
</html>

