<?php
$options = array('query' => $this->params()->fromQuery());
?>
<?php if ($this->pageCount > 1): ?>
    <nav class="text-center">
        <ul class="pagination">
            <li <?php echo (!isset($this->previous)) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo (isset($this->previous)) ? $this->url($this->route, array('action' => $this->action, 'page' => $this->first), $options) : '#'; ?>"
                   aria-label="<?php echo $this->translate('First'); ?>">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li <?php echo (!isset($this->previous)) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo (isset($this->previous)) ? $this->url($this->route, array('action' => $this->action, 'page' => $this->previous), $options) : '#'; ?>"
                   aria-label="<?php echo $this->translate('Previous'); ?>">
                    <span aria-hidden="true">&lsaquo;</span>
                </a>                
            </li>

            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>>
                    <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'page' => $page), array('query' => $this->params()->fromQuery())); ?>">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php endforeach; ?>

            <li <?php echo (!isset($this->next)) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo (isset($this->next)) ? $this->url($this->route, array('action' => $this->action, 'page' => $this->next), $options) : '#'; ?>"
                   aria-label="<?php echo $this->translate('Next'); ?>">
                    <span aria-hidden="true">&rsaquo;</span>
                </a>
            </li>
            <li <?php echo (!isset($this->next)) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo (isset($this->next)) ? $this->url($this->route, array('action' => $this->action, 'page' => $this->last), $options) : '#'; ?>"
                   aria-label="<?php echo $this->translate('Last'); ?>">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
<?php endif; ?>