<?php
/**
 * View script for about page
 *
 * There are no variables passed to this view script at this point.
 */
$title = $this->translate('About');
$this->headTitle($title);
?>
<div class="container" xmlns="http://www.w3.org/1999/html">
  <div class="row">
    <div class="col-md-12">
      <h1> <?php echo($title) ?></h1>
      <h3><?php echo $this->translate('Was ist CERTIFICAT?') ?></h3>

      <p><?php echo $this->translate('CERTIFICAT gibt Organisationen die Möglichkeit den Teilnehmern ihrer Projekte und Weiterbildungen oder ihren ehrenamtlichen Mitarbeitern Kompetenzbescheinigungen auszustellen.') ?></p>

      <p><?php echo $this->translate('Die bescheinigten Kompetenzen beruhen auf einer Basisliste die mithilfe der CERTIFICAT-Partner ausgearbeitet wurde und so den Weg für ein einheitliches Kompetenzvokabular legt.') ?></p>

      <p><?php echo $this->translate('Die Teilnehmer können ihre Kompetenzen und Zertifikate auf CERTIFICAT einsehen und in Verbindung mit ePortfolio nutzen um so eine komplette Bewerbung zu erstellen und ihren Werdegang zu dokumentieren.') ?></p>

      <h3><?php echo $this->translate('Für wen ist CERTIFICAT gedacht?') ?></h3>

      <p><?php echo $this->translate('CERTIFICAT richtet sich an alle die Interesse an Weiterbildungsmaßnahmen und Aktivitäten im non-formalen Bildungsbereich oder an ehrenamtlichem Engagement haben.') ?></p>

      <p><?php echo $this->translate('Als Organisation anmelden können sich alle Vereine, Institutionen und Einrichtungen, die in diesem Bereich tätig sind und für Weiterbildungskurse, Projekte oder andere Aktivitäten regelmäßig oder punktuell Zertifikate ausstellen, um den betreffenden Teilnehmern bzw. ehrenamtlichen Mitarbeitern geförderte Kompetenzen zu bescheinigen. CERTIFICAT eignet sich sowohl für das Ausstellen von Zertifikaten an eine größere Gruppe als auch für die individuelle Bescheinigung von Kompetenzen. Neben der Erstellung, vereinfacht CERTIFICAT auch die Verwaltung von Teilnehmerlisten und Zertifikaten.') ?></p>

      <p><?php echo $this->translate('Registrierte Teilnehmer können ihre Kompetenzen und Zertifikate auf CERTIFICAT einsehen. Geförderte Kompetenzen können später individuell und europass-konform in den Lebenslauf bei der Erstellung einer Bewerbung mittels ePortfolio eingebunden werden.') ?></p>

      <h3><?php echo $this->translate('Wofür ist CERTIFICAT gedacht?') ?></h3>

      <p><?php echo $this->translate('Auch außerhalb von Schule und Beruf kann man viel lernen, sei es durch die gezielte Teilnahme an Weiterbildungsmaßen, durch ehrenamtliches Engagement oder die Mitgestaltung von außerschulischen Projekten. CERTIFICAT dient dazu Kompetenzen die auf diese Art und Weise gefördert wurden zu bescheinigen und sie dadurch hervorzuheben.') ?></p>

      <p><?php echo $this->translate('Das gemeinsam festgelegte Kompetenzvokabular vereinfacht die Kommunikation innerhalb des außerschulischen und ehrenamtlichen Sektors und vermittelt auch nach außen ein einheitliches Bild. Das gemeinsame Vokabular und die einheitliche Grafik erhöhen den Wiedererkennungswert bei potentiellen Arbeitgebern oder im Zusammenhang mit einer Unibewerbung.') ?></p>

      <p><?php echo $this->translate('Nicht zuletzt ist CERTIFICAT ein Tool das zur Aufwertung der Vita von Jugendlichen und Erwachsenen die sich in ihrer Freizeit für gemeinnützige Zwecke einsetzen oder sich zusätzlichen Herausforderungen stellen.') ?></p>


      <h3><?php echo $this->translate('Wer arbeitet mit CERTIFICAT?') ?></h3>

      <p><?php echo $this->translate('CERTIFICAT kann von Organisationen in vielen unterschiedlichen Bereichen angewendet werden: Kreativität, Gesundheit, Soziales, Umwelt, Politik, ….') ?></p>

      <p><?php echo $this->translate('CERTIFICAT ist außerdem Teil des von der Association du bénévolat ausgearbeiteten Labels für Ehrenamtlichkeit.') ?></p>

      <p><b><?php echo $this->translate('Partnerorganisationen von CERTIFICAT:') ?></b></br>
        <?php echo $this->translate('Agence du bénévolat http://www.benevolat.public.lu/de/index.html') ?> </br>
        <?php echo $this->translate('Jugendkonferenz http://www.cgjl.lu/de/') ?></p>

      <p><?php echo $this->translate('(Sobald das Tool genutzt wird : Übersicht der angeschlossenen Organisationen mit link zur Website)') ?></p>

      <h3><?php echo $this->translate('Werde ein Teil von CERTIFICAT!') ?></h3>

      <p><?php echo $this->translate('CERTIFICAT für ORGANISATIONEN: Eine Organisation die CERTIFICAT nutzen möchte erstellt zunächst ein Administratorprofil das von der zuständigen SNJ- Stelle validiert wird. Nach der Validierung kann der Administrator das Tool uneingeschränkt nutzen und auch weitere „Editor“-Profile erstellen um Mitarbeitern in der Organisation das Erstellen von Kompetenzbescheinigungen zu ermöglichen.') ?></p>

      <p><?php echo $this->translate('CERTIFICAT für TEILNEHMER: Jeder der an Aktivitäten teilnimmt oder zu Projekten beiträgt, die von einer CERTIFICAT Organisation durchgeführt werden, kann seine Organisation bitten ein Zertifikat auszustellen und diese dann durch das Anlegen eines Kontos verwalten.') ?></p>
    </div>
  </div>
  <!-- row -->
</div><!-- container -->